import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

// const xdprime = localFont({
//   src:[{
//     path:"../../public/fonts/XDPrime-Regular.otf",
//     weight: "700"
//   }

//   ] ,

//   variable: "--font-xdprime",
// });

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.variable}>{children}</body>
    </html>
  );
}
