import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const XDPrime = localFont({
  src: [
    {
      path: "../public/fonts/XDPrime-Regular.otf",
      weight: "400",
    },
    {
      path: "../public/fonts/XDPrime-Bold.otf",
      weight: "700",
    },
  ],
  display: "swap",
  variable: "--font-xdprime",
});

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* 
        1. Initialize the global variable into css
        2. Add font-sans class to apply the custom font-family
      */}
      <body className={`${XDPrime.variable} ${inter.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
